name: Placeholder CI

# Trigger on any push to main
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo placeholder
        run: echo "✅ CI is wired up correctly!"
